apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bot-project.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tele-token: {{ .Values.telegram.token | b64enc }}
